fetch("https://www.instagram.com/api/v1/web/comments/3705079064316891103/add/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,it-IT;q=0.8,it;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "content-type": "application/x-www-form-urlencoded",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-prefers-color-scheme": "light",
    "sec-ch-ua": "\"Not;A=Brand\";v=\"99\", \"Google Chrome\";v=\"139\", \"Chromium\";v=\"139\"",
    "sec-ch-ua-full-version-list": "\"Not;A=Brand\";v=\"99.0.0.0\", \"Google Chrome\";v=\"139.0.7258.128\", \"Chromium\";v=\"139.0.7258.128\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "\"\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-platform-version": "\"19.0.0\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-asbd-id": "359341",
    "x-csrftoken": "uGWSOELAb7txjWS6EjKUp88pPMFTGGuo",
    "x-ig-app-id": "936619743392459",
    "x-ig-www-claim": "hmac.AR0hNXs-2vmUDSXetHaCqNEp3UPnsPxOKfYx1PYRP9ANUskk",
    "x-instagram-ajax": "1026232158",
    "x-requested-with": "XMLHttpRequest",
    "x-web-session-id": "no53ze:lymgoe:jinr0i"
  },
  "referrer": "https://www.instagram.com/p/DNrFcdVWE_f/",
  "body": "comment_text=top+%F0%9F%92%AF&jazoest=22718",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});