fetch("https://www.instagram.com/api/v1/web/accounts/login/ajax/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9",
    "cache-control": "no-cache",
    "content-type": "application/x-www-form-urlencoded",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-prefers-color-scheme": "light",
    "sec-ch-ua": "\"Not;A=Brand\";v=\"99\", \"Google Chrome\";v=\"139\", \"Chromium\";v=\"139\"",
    "sec-ch-ua-full-version-list": "\"Not;A=Brand\";v=\"99.0.0.0\", \"Google Chrome\";v=\"139.0.7258.128\", \"Chromium\";v=\"139.0.7258.128\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "\"\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-platform-version": "\"19.0.0\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-asbd-id": "359341",
    "x-csrftoken": "hYZZeTjHAxJXGuBVvSmbZZ",
    "x-ig-app-id": "936619743392459",
    "x-ig-www-claim": "0",
    "x-instagram-ajax": "1026160724",
    "x-mid": "1pncamvvos6yq1x70gei67gthcnuhu1m1484p8o1uz8j457vl6vx",
    "x-requested-with": "XMLHttpRequest",
    "x-web-device-id": "218F0DE0-E667-49B0-9FAA-0D23E699FFA8",
    "x-web-session-id": "wfwjp9:kkkdvt:pdnms7"
  },
  "referrer": "https://www.instagram.com/",
  "body": "enc_password=%23PWD_INSTAGRAM_BROWSER%3A10%3A1755806990%3AATZQAOTfx7GQSnYVtABFdeqhTGyWSp0Qeb%2FzAH3kVVMh14xlaRifhL%2FGj4ETS%2BNq7THSzvHCCUnthJzszibAsHEuN2o74P%2BPJBwGjcTajmMwRyjSuUX3LxJv9BuCZw4ASporJpRPB%2BJqrby78XFlH1BWnM9Yg%2BlqQg%3D%3D&caaF2DebugGroup=0&isPrivacyPortalReq=false&loginAttemptSubmissionCount=0&optIntoOneTap=false&queryParams=%7B%7D&trustedDeviceRecords=%7B%7D&username=vincenzopirozzi.developer_2&jazoest=22011",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});