fetch("https://www.instagram.com/api/v1/friendships/destroy/644768214/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,it-IT;q=0.8,it;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "content-type": "application/x-www-form-urlencoded",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-prefers-color-scheme": "light",
    "sec-ch-ua": "\"Not;A=Brand\";v=\"99\", \"Google Chrome\";v=\"139\", \"Chromium\";v=\"139\"",
    "sec-ch-ua-full-version-list": "\"Not;A=Brand\";v=\"99.0.0.0\", \"Google Chrome\";v=\"139.0.7258.128\", \"Chromium\";v=\"139.0.7258.128\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": "\"\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-ch-ua-platform-version": "\"19.0.0\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-asbd-id": "359341",
    "x-csrftoken": "wXnpji4ww89CmMWfUFBYc28WwIHIoivD",
    "x-ig-app-id": "936619743392459",
    "x-ig-www-claim": "hmac.AR0_eDs2CvwesGHfluAADTrcOpnm7KvsqmfgyDHxk34UxnBL",
    "x-instagram-ajax": "1026178298",
    "x-requested-with": "XMLHttpRequest",
    "x-web-session-id": "5tiy0a:7ot9wz:9eo2xj"
  },
  "referrer": "https://www.instagram.com/vincenzopirozzi.developer_2/following/",
  "body": "container_module=profile&nav_chain=PolarisProfilePostsTabRoot%3AprofilePage%3A1%3Avia_cold_start%2CPolarisProfilePostsTabRoot%3AprofilePage%3A2%3Aunexpected&user_id=644768214&jazoest=22826",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});